# GitHub overrided
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#  noscript: false
# kramdown:
#  math_engine: mathjax

encoding: utf-8
timezone: Japan/Tokyo
gems:
 - jekyll-assets

title: 式々頁
email:
description: 式々の開発ログ
baseurl:
url: "http://4ki2.github.io"
twitter_username: 4ki2
github_username:  4ki2
