# GitHub overrided
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#  noscript: false
# kramdown:
#  math_engine: mathjax

encoding: utf-8
timezone: Japan/Tokyo
title: 4ki2.github.io
email:
description: GitHubリポジトリ一覧。このページです。
baseurl:
url: "http://4ki2.github.io"
twitter_username: 4ki2
github_username:  4ki2

