# GitHub overrided settings
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#  noscript: false
# kramdown:
#  math_engine: mathjax

# My settings
encoding: utf-8
timezone: Japan/Tokyo
# safe: false
# incremental: true
# verbose: true
# regenerate: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

title: 式々頁
email:
description: > # this means to ignore newlines until "baseurl:"
  式々の開発ログ
baseurl:
url: "http://4ki2.github.io"
twitter_username: 4ki2
github_username:  4ki2

